---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml

#
# Cluster Settings
#

# nodes form a cluster by having the same cluster name
cluster.name: central-monitor

# The node name defaults to the hostname of the machine when Elasticsearch starts
node.name: ${ES_HOST}

network.host: 0.0.0.0

# eligible master nodes to be selected
cluster.initial_master_nodes:
  - ${ES_HOST}
  - ${ES_DISCOVERY_SEED_HOST_1}
  - ${ES_DISCOVERY_SEED_HOST_2}

# discover and connect to other nodes in the same cluster
discovery.seed_hosts:
  - ${ES_DISCOVERY_SEED_HOST_1}
  - ${ES_DISCOVERY_SEED_HOST_2}

bootstrap.memory_lock: true

#
# X-Pack Settings
#
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html

# License
xpack.license.self_generated.type: trial

# enable Elasticsearch monitoring and data collection features
xpack.monitoring.collection.enabled: true
xpack.monitoring.history.duration: 7d

# Security
xpack.security.enabled: true

#
# Transport Layer Security (TLS) settings
#

# Transport Protocol (inter-node communication)
# note: production nodes won't start without this feature
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: certs/${ES_HOST}/${ES_HOST}.key
xpack.security.transport.ssl.certificate: certs/${ES_HOST}/${ES_HOST}.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt

# HTTP Protocol (communication between ES and Kibana / Logstash
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key: certs/${ES_HOST}/${ES_HOST}.key
xpack.security.http.ssl.certificate: certs/${ES_HOST}/${ES_HOST}.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt

#
# Azure snapshot repository settings
#

# secure settings (account and key) must be stored in the keystore
azure.client.default.timeout: 10s
azure.client.default.max_retries: 7
azure.client.default.endpoint_suffix: core.windows.net

#
# SAML single-sign-on
# https://www.elastic.co/guide/en/elasticsearch/reference/current/saml-guide-stack.html
#

# enable token service
xpack.security.authc.token.enabled: true

# create a SAML realm
xpack.security.authc.realms.saml.saml1:
  order: 2
  idp.metadata.path: saml/Jeffrey-Test.xml
  idp.entity_id: "https://sts.windows.net/2407f5a1-de4b-4c0c-b30e-9cd9790f6d6c/"
  sp.entity_id:  "https://elk.cloud.dje-intern.de"
  sp.acs: "https://elk.cloud.dje-intern.de/api/security/saml/callback"
  sp.logout: "https://elk.cloud.dje-intern.de/logout"
  attributes.principal: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  attributes.groups: "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
  attributes.mail: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"