---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml

#
# Cluster Settings
#

# nodes form a cluster by having the same cluster name
cluster.name: elastic-cluster

# The node name defaults to the hostname of the machine when Elasticsearch starts
node.name: es

network.host: 0.0.0.0

# instruct Elasticsearch to form a single-node cluster
discovery.type: single-node

bootstrap.memory_lock: true

#
# X-Pack Settings
#
# see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html

# License
xpack.license.self_generated.type: trial

# enable Elasticsearch monitoring and data collection features
xpack.monitoring.collection.enabled: true
xpack.monitoring.history.duration: 7d

# Security
xpack.security.enabled: true


# Transport Layer Security (TLS) settings
# https://www.elastic.co/guide/en/elasticsearch/reference/current/security-basic-setup.html#security-basic-setup

# Transport Protocol (inter-node communication)
# note: production nodes won't start without this feature
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: certs/es/es.key
xpack.security.transport.ssl.certificate: certs/es/es.crt
xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt

# HTTP Protocol (communication between ES and Kibana / Logstash)
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key: certs/es/es.key
xpack.security.http.ssl.certificate: certs/es/es.crt
xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt