version: "3.7"

services:

  # The service creates Elasticsearch Certificate Authority (CA)
  # and certificates for each ES node signed by that CA.
  #
  # Generated certificates and keys are stored in ./certs
  #
  # If certs already exist then the service exits immediately.
  es_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: setup_es_certs
    command: bash /certs.sh
    user: "0"
    volumes:
      - ./certs:/certs
      - ./setup/elasticsearch/certs.sh:/certs.sh